### ISSUE TITLE
Incorrect validation of payload from the execution layer

### ISSUE THREAD

**Issue by infloop** [lidofinance/validator-ejector#93]
We got this error message in ejector:
2023-09-29 14:43:27 error: Startup error {"validatedData":{"jsonrpc":"2.0","result":{"startingBlock":"0x0","currentBlock":"0x9539aa","highestBlock":"0x9539aa"},"id":1},"message":"Invalid bool input: \"[object Object]\"","name":"Error","stack":"Error: Invalid bool input: \"[object Object]\"\n    at file:///home/zzz/code/gatewayfm/validator-ejector/node_modules/lido-nanolib/dist/validator/makers.js:17:19\n    at syncingDTO (file:///home/zzz/code/gatewayfm/validator-ejector/dist/src/services/execution-api/dto.js:2:37)\n    at syncing (file:///home/zzz/code/gatewayfm/validator-ejector/dist/src/services/execution-api/service.js:22:28)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async Object.checkSync (file:///home/zzz/code/gatewayfm/validator-ejector/dist/src/services/execution-api/service.js:27:13)\n    at async Object.run (file:///home/zzz/code/gatewayfm/validator-ejector/dist/src/app/service.js:8:9)\n    at async Object.run (file:///home/zzz/code/gatewayfm/validator-ejector/dist/src/app/module.js:88:13)\n    at async bootstrap (file:///home/zzz/code/gatewayfm/validator-ejector/dist/src/index.js:10:9)"}

and the EL is synced and it returned with
{"jsonrpc":"2.0","result":{"startingBlock":"0x0","currentBlock":"0x9539a6","highestBlock":"0x9539a6"},"id":1}%

**Comment by infloop** [comment]
Nethermind returns 
{"jsonrpc":"2.0","result":{"startingBlock":"0x0","currentBlock":"0x9539a6","highestBlock":"0x9539a6"},"id":1} when it's synced using fastsync. 

But usually EL returns {"jsonrpc":"2.0","id":1,"result":false} when they are synced.

**Comment by chasingrainbows** [comment]
Nethermind has been informed about it, and that it won't be fixed in the validator-ejector.

**Comment by chasingrainbows** [comment]
Nethermind has been informed about it, and that it won't be fixed in the validator-ejector. However, error message will be improved.
